# Generated by Django 5.2.7 on 2025-10-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_banned_customuser_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(default='a mystery...', max_length=240, verbose_name='about'),
        ),
    ]
