# Generated by Django 5.2.7 on 2025-11-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_list_csvfile_medialistrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medialistrow',
            old_name='name',
            new_name='title',
        ),
    ]
