# Generated by Django 5.2.7 on 2025-11-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_rename_name_medialistrow_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialistrow',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'Series')], default='Movie', max_length=20),
            preserve_default=False,
        ),
    ]
